---
- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Add repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true 
    state: present
  loop: "{{ common_repositories }}"

- name: "Ensure that {{ item }} is installed"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
