---
- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure that acl is installed
  become: true
  ansible.builtin.apt:
    name: acl
    state: present  

- name: Ensure that curl is installed
  become: true
  ansible.builtin.apt:
    name: curl
    state: present

- name: Ensure that git is installed
  become: true
  ansible.builtin.apt:
    name: git
    state: present

- name: Ensure that wget is installed
  become: true
  ansible.builtin.apt:
    name: wget
    state: present
