---
- name: Install repositories and packages
  ansible.builtin.include_tasks: install.yml
  when: installer_uninstall == false

- name: Uninstall repositories and packages
  ansible.builtin.include_tasks: uninstall.yml
  when: installer_uninstall == true
