---
- name: Ensure that package is uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ installer_autoremove }}"
    purge: "{{ installer_purge }}"
    state: absent
  loop: "{{ installer_packages }}"

- name: Remove repository if it exists
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
  loop: "{{ installer_repositories }}"

- name: Update the repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
